version: "3.8"

services:
  ####################################
  ###    APPLICATION SERVICES      ###
  ####################################

  # MongoDB container
  mongo:
    image: mongo:latest
    container_name: dev_mongo
    ports:
      - "27017:27017"

  # Adminer for database
  adminer:
    image: adminer
    container_name: dev_adminer
    links:
      - mongo
    restart: always
    ports:
      - "8081:8080"  # port for adminer 8081
